// Mock data pour les guides
export const mockGuides = [
  {
    id: '1',
    name: 'Amadou Diallo',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150',
    languages: ['Français', 'Anglais', 'Wolof'],
    specialties: ['Histoire', 'Culture', 'Gastronomie'],
    rating: 4.9,
    reviews: 127,
    price: '25,000 FCFA',
    location: 'Dakar',
    isVerified: true,
    availability: 'Disponible',
    description: 'Guide expérimenté spécialisé dans l\'histoire et la culture du Sénégal. Passionné par le partage de connaissances.',
    experience: '8 ans',
    toursCompleted: 245,
    responseTime: '2h',
    badge: 'Guide Premium',
    featured: true,
    type: 'Certifiés'
  },
  {
    id: '2',
    name: 'Fatou Sarr',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150',
    languages: ['Français', 'Anglais', 'Sérère'],
    specialties: ['Nature', 'Écologie', 'Randonnée'],
    rating: 4.8,
    reviews: 89,
    price: '22,000 FCFA',
    location: 'Saint-Louis',
    isVerified: true,
    availability: 'Disponible',
    description: 'Guide nature passionnée par l\'écologie et les randonnées dans les parcs nationaux du Sénégal.',
    experience: '5 ans',
    toursCompleted: 156,
    responseTime: '1h',
    badge: 'Guide Certifié',
    featured: false,
    type: 'Diplômés'
  },
  {
    id: '3',
    name: 'Moussa Ba',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150',
    languages: ['Français', 'Wolof', 'Pulaar'],
    specialties: ['Artisanat', 'Traditions', 'Musique'],
    rating: 4.7,
    reviews: 67,
    price: '20,000 FCFA',
    location: 'Thiès',
    isVerified: true,
    availability: 'Disponible',
    description: 'Guide local expert en artisanat traditionnel et musique sénégalaise. Connaît parfaitement les traditions.',
    experience: '6 ans',
    toursCompleted: 134,
    responseTime: '3h',
    badge: 'Guide Local',
    featured: false,
    type: 'Local'
  },
  {
    id: '4',
    name: 'Aïcha Diop',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150',
    languages: ['Français', 'Anglais', 'Espagnol'],
    specialties: ['Architecture', 'Art', 'Photographie'],
    rating: 4.9,
    reviews: 98,
    price: '28,000 FCFA',
    location: 'Dakar',
    isVerified: true,
    availability: 'Disponible',
    description: 'Guide spécialisée en architecture coloniale et art contemporain. Parfaite pour les amateurs d\'art.',
    experience: '7 ans',
    toursCompleted: 189,
    responseTime: '1h',
    badge: 'Guide Premium',
    featured: true,
    type: 'Formations professionnelles'
  },
  {
    id: '5',
    name: 'Ibrahima Ndiaye',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150',
    languages: ['Français', 'Anglais', 'Wolof'],
    specialties: ['Sport', 'Aventure', 'Plage'],
    rating: 4.6,
    reviews: 45,
    price: '18,000 FCFA',
    location: 'Saly',
    isVerified: true,
    availability: 'Disponible',
    description: 'Guide sportif spécialisé dans les activités nautiques et les aventures en bord de mer.',
    experience: '4 ans',
    toursCompleted: 78,
    responseTime: '2h',
    badge: 'Guide Sportif',
    featured: false,
    type: 'Certifiés'
  },
  {
    id: '6',
    name: 'Mariama Fall',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150',
    languages: ['Français', 'Anglais', 'Wolof'],
    specialties: ['Religion', 'Spiritualité', 'Pèlerinage'],
    rating: 4.8,
    reviews: 56,
    price: '24,000 FCFA',
    location: 'Touba',
    isVerified: true,
    availability: 'Disponible',
    description: 'Guide spirituel spécialisé dans les pèlerinages et l\'histoire religieuse du Sénégal.',
    experience: '9 ans',
    toursCompleted: 167,
    responseTime: '1h',
    badge: 'Guide Spirituel',
    featured: false,
    type: 'Diplômés'
  }
];

// Mock data pour les événements
export const mockEvents = [
  // ÉVÉNEMENTS SPORTIFS
  {
    id: '1',
    title: 'Match de Football: Sénégal vs Maroc',
    description: 'Match amical entre les Lions de la Téranga et les Lions de l\'Atlas',
    date: '2024-04-25',
    time: '18:00',
    location: 'Stade Léopold Sédar Senghor',
    category: 'Football',
    price: '25,000 FCFA',
    image: 'https://images.pexels.com/photos/1190298/pexels-photo-1190298.jpeg?auto=compress&cs=tinysrgb&w=400',
    organizer: 'Fédération Sénégalaise de Football',
    capacity: 60000,
    registered: 45000,
    type: 'sport',
    isLive: true,
    liveData: {
      score: '2-1',
      minute: '67',
      status: 'En cours',
      homeTeam: 'Sénégal',
      awayTeam: 'Maroc',
      homeScore: 2,
      awayScore: 1,
      events: [
        { minute: '23', type: 'goal', team: 'home', player: 'Sadio Mané' },
        { minute: '45', type: 'goal', team: 'away', player: 'Hakim Ziyech' },
        { minute: '67', type: 'goal', team: 'home', player: 'Ismaila Sarr' }
      ]
    }
  },
  {
    id: '2',
    title: 'Tournoi de Lutte Traditionnelle',
    description: 'Grand tournoi de lutte sénégalaise avec les meilleurs lutteurs du pays',
    date: '2024-04-28',
    time: '16:00',
    location: 'Arena de Lutte de Dakar',
    category: 'Lutte',
    price: '10,000 FCFA',
    image: 'https://images.pexels.com/photos/1190297/pexels-photo-1190297.jpeg?auto=compress&cs=tinysrgb&w=400',
    organizer: 'Fédération Sénégalaise de Lutte',
    capacity: 15000,
    registered: 12000,
    type: 'sport',
    isLive: false
  },
  {
    id: '3',
    title: 'Championnat de Basketball',
    description: 'Finale du championnat national de basketball',
    date: '2024-05-05',
    time: '20:30',
    location: 'Palais des Sports de Dakar',
    category: 'Basketball',
    price: '12,000 FCFA',
    image: 'https://images.pexels.com/photos/1190296/pexels-photo-1190296.jpeg?auto=compress&cs=tinysrgb&w=400',
    organizer: 'Fédération Sénégalaise de Basketball',
    capacity: 5000,
    registered: 4200,
    type: 'sport',
    isLive: false
  },
  {
    id: '4',
    title: 'Marathon International de Dakar',
    description: 'Course à pied de 42km à travers les rues de Dakar',
    date: '2024-05-12',
    time: '06:00',
    location: 'Place de l\'Indépendance',
    category: 'Athlétisme',
    price: '15,000 FCFA',
    image: 'https://images.pexels.com/photos/1190295/pexels-photo-1190295.jpeg?auto=compress&cs=tinysrgb&w=400',
    organizer: 'Fédération Sénégalaise d\'Athlétisme',
    capacity: 3000,
    registered: 2100,
    type: 'sport',
    isLive: false
  },
  {
    id: '5',
    title: 'Tournoi de Tennis de Saly',
    description: 'Compétition de tennis sur les courts de Saly',
    date: '2024-05-18',
    time: '14:00',
    location: 'Club de Tennis de Saly',
    category: 'Tennis',
    price: '8,000 FCFA',
    image: 'https://images.pexels.com/photos/1190294/pexels-photo-1190294.jpeg?auto=compress&cs=tinysrgb&w=400',
    organizer: 'Club de Tennis de Saly',
    capacity: 500,
    registered: 320,
    type: 'sport',
    isLive: false
  },
  {
    id: '6',
    title: 'Championnat de Natation',
    description: 'Compétition de natation en piscine olympique',
    date: '2024-05-25',
    time: '09:00',
    location: 'Piscine Olympique de Dakar',
    category: 'Natation',
    price: '6,000 FCFA',
    image: 'https://images.pexels.com/photos/1190293/pexels-photo-1190293.jpeg?auto=compress&cs=tinysrgb&w=400',
    organizer: 'Fédération Sénégalaise de Natation',
    capacity: 800,
    registered: 450,
    type: 'sport',
    isLive: false
  },

  // ÉVÉNEMENTS CULTURELS ET AUTRES
  {
    id: '7',
    title: 'Festival de Jazz de Saint-Louis',
    description: 'Découvrez la musique jazz dans la ville historique de Saint-Louis',
    date: '2024-04-15',
    time: '20:00',
    location: 'Saint-Louis',
    category: 'Musique',
    price: '15,000 FCFA',
    image: 'https://images.pexels.com/photos/1190292/pexels-photo-1190292.jpeg?auto=compress&cs=tinysrgb&w=400',
    organizer: 'Association Jazz Saint-Louis',
    capacity: 500,
    registered: 320,
    type: 'other',
    isLive: false
  },
  {
    id: '8',
    title: 'Foire Internationale de Dakar',
    description: 'Exposition des produits locaux et internationaux',
    date: '2024-04-20',
    time: '09:00',
    location: 'Dakar',
    category: 'Culture',
    price: '5,000 FCFA',
    image: 'https://images.pexels.com/photos/1190291/pexels-photo-1190291.jpeg?auto=compress&cs=tinysrgb&w=400',
    organizer: 'CCI Dakar',
    capacity: 1000,
    registered: 750,
    type: 'other',
    isLive: false
  },
  {
    id: '9',
    title: 'Semaine Culturelle de Thiès',
    description: 'Festival culturel avec musique, danse et artisanat traditionnel',
    date: '2024-05-01',
    time: '19:00',
    location: 'Thiès',
    category: 'Culture',
    price: '8,000 FCFA',
    image: 'https://images.pexels.com/photos/1190290/pexels-photo-1190290.jpeg?auto=compress&cs=tinysrgb&w=400',
    organizer: 'Mairie de Thiès',
    capacity: 2000,
    registered: 1500,
    type: 'other',
    isLive: false
  },
  {
    id: '10',
    title: 'Festival de Gastronomie Sénégalaise',
    description: 'Découvrez les saveurs authentiques du Sénégal',
    date: '2024-05-08',
    time: '12:00',
    location: 'Dakar',
    category: 'Gastronomie',
    price: '12,000 FCFA',
    image: 'https://images.pexels.com/photos/1190289/pexels-photo-1190289.jpeg?auto=compress&cs=tinysrgb&w=400',
    organizer: 'Association des Restaurateurs',
    capacity: 800,
    registered: 520,
    type: 'other',
    isLive: false
  },
  {
    id: '11',
    title: 'Exposition d\'Art Contemporain',
    description: 'Exposition d\'œuvres d\'artistes sénégalais contemporains',
    date: '2024-05-15',
    time: '10:00',
    location: 'Musée des Civilisations Noires',
    category: 'Art',
    price: '3,000 FCFA',
    image: 'https://images.pexels.com/photos/1190288/pexels-photo-1190288.jpeg?auto=compress&cs=tinysrgb&w=400',
    organizer: 'Musée des Civilisations Noires',
    capacity: 300,
    registered: 180,
    type: 'other',
    isLive: false
  },
  {
    id: '12',
    title: 'Conférence sur l\'Entrepreneuriat',
    description: 'Formation et conférence sur l\'entrepreneuriat au Sénégal',
    date: '2024-05-22',
    time: '14:00',
    location: 'CCI Dakar',
    category: 'Formation',
    price: 'Gratuit',
    image: 'https://images.pexels.com/photos/1190287/pexels-photo-1190287.jpeg?auto=compress&cs=tinysrgb&w=400',
    organizer: 'CCI Dakar',
    capacity: 200,
    registered: 150,
    type: 'other',
    isLive: false
  },
  {
    id: '13',
    title: 'Festival de Danse Traditionnelle',
    description: 'Spectacle de danses traditionnelles du Sénégal',
    date: '2024-05-30',
    time: '20:30',
    location: 'Théâtre National Daniel Sorano',
    category: 'Culture',
    price: '10,000 FCFA',
    image: 'https://images.pexels.com/photos/1190286/pexels-photo-1190286.jpeg?auto=compress&cs=tinysrgb&w=400',
    organizer: 'Théâtre National',
    capacity: 600,
    registered: 420,
    type: 'other',
    isLive: false
  },
  {
    id: '14',
    title: 'Tournoi de Pétanque',
    description: 'Compétition de pétanque entre équipes locales',
    date: '2024-06-02',
    time: '15:00',
    location: 'Place de la République',
    category: 'Sport',
    price: '5,000 FCFA',
    image: 'https://images.pexels.com/photos/1190285/pexels-photo-1190285.jpeg?auto=compress&cs=tinysrgb&w=400',
    organizer: 'Fédération Sénégalaise de Pétanque',
    capacity: 100,
    registered: 80,
    type: 'sport',
    isLive: false
  },
  {
    id: '15',
    title: 'Festival de Mode Africaine',
    description: 'Défilé de mode mettant en valeur les créateurs africains',
    date: '2024-06-08',
    time: '19:00',
    location: 'Hôtel Terrou-Bi',
    category: 'Mode',
    price: '20,000 FCFA',
    image: 'https://images.pexels.com/photos/1190284/pexels-photo-1190284.jpeg?auto=compress&cs=tinysrgb&w=400',
    organizer: 'Association des Créateurs de Mode',
    capacity: 400,
    registered: 280,
    type: 'other',
    isLive: false
  },
  {
    id: '16',
    title: 'Championnat de Volleyball',
    description: 'Finale du championnat national de volleyball',
    date: '2024-06-15',
    time: '18:00',
    location: 'Palais des Sports de Dakar',
    category: 'Volleyball',
    price: '8,000 FCFA',
    image: 'https://images.pexels.com/photos/1190283/pexels-photo-1190283.jpeg?auto=compress&cs=tinysrgb&w=400',
    organizer: 'Fédération Sénégalaise de Volleyball',
    capacity: 3000,
    registered: 2100,
    type: 'sport',
    isLive: false
  }
];

// Mock data pour les hébergements
export const mockAccommodations = [
  {
    id: '1',
    name: 'Hôtel Terrou-Bi',
    description: 'Hôtel de luxe en bord de mer avec vue panoramique sur l\'océan Atlantique',
    type: 'Hôtel',
    location: 'Dakar',
    rating: 4.8,
    reviews: 245,
    price: '85,000 FCFA',
    image: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150',
    amenities: ['WiFi', 'Piscine', 'Parking', 'Restaurant', 'Spa', 'Gym', 'Climatisation'],
    featured: true,
    availability: 'Disponible',
    capacity: 200,
    checkIn: '15:00',
    checkOut: '12:00'
  },
  {
    id: '2',
    name: 'Restaurant Le Ngor',
    description: 'Restaurant gastronomique spécialisé dans la cuisine sénégalaise traditionnelle',
    type: 'Restaurant',
    location: 'Dakar',
    rating: 4.6,
    reviews: 189,
    price: '12,000 FCFA',
    image: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150',
    amenities: ['WiFi', 'Parking', 'Terrasse', 'Climatisation'],
    featured: false,
    availability: 'Ouvert',
    capacity: 80
  },
  {
    id: '3',
    name: 'Auberge de la Langue de Barbarie',
    description: 'Auberge écologique au cœur de la réserve naturelle de Saint-Louis',
    type: 'Auberge',
    location: 'Saint-Louis',
    rating: 4.7,
    reviews: 156,
    price: '25,000 FCFA',
    image: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150',
    amenities: ['WiFi', 'Parking', 'Restaurant', 'Climatisation'],
    featured: true,
    availability: 'Disponible',
    capacity: 50,
    checkIn: '14:00',
    checkOut: '11:00'
  },
  {
    id: '4',
    name: 'Villa Saly Beach',
    description: 'Villa privée avec accès direct à la plage de Saly',
    type: 'Villa',
    location: 'Saly',
    rating: 4.9,
    reviews: 98,
    price: '120,000 FCFA',
    image: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150',
    amenities: ['WiFi', 'Piscine', 'Parking', 'Cuisine', 'Climatisation', 'Plage privée'],
    featured: true,
    availability: 'Disponible',
    capacity: 8,
    checkIn: '16:00',
    checkOut: '10:00'
  },
  {
    id: '5',
    name: 'Résidence Les Almadies',
    description: 'Résidence moderne avec appartements meublés en centre-ville',
    type: 'Résidence',
    location: 'Dakar',
    rating: 4.4,
    reviews: 203,
    price: '45,000 FCFA',
    image: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150',
    amenities: ['WiFi', 'Parking', 'Cuisine', 'Climatisation', 'Gym'],
    featured: false,
    availability: 'Disponible',
    capacity: 100,
    checkIn: '15:00',
    checkOut: '12:00'
  },
  {
    id: '6',
    name: 'Restaurant Chez Loutcha',
    description: 'Restaurant traditionnel spécialisé dans le thiéboudiène et les plats locaux',
    type: 'Restaurant',
    location: 'Thiès',
    rating: 4.5,
    reviews: 134,
    price: '8,000 FCFA',
    image: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150',
    amenities: ['WiFi', 'Parking', 'Terrasse'],
    featured: false,
    availability: 'Ouvert',
    capacity: 60
  }
];

// Mock data pour les articles
export const mockArticles = [
  {
    id: '1',
    title: 'L\'Histoire de Gorée : Porte de l\'Esclavage',
    excerpt: 'Découvrez l\'histoire tragique et l\'importance de l\'île de Gorée dans la traite des esclaves.',
    content: 'Contenu complet sur Gorée...',
    image: 'https://images.pexels.com/photos/8828593/pexels-photo-8828593.jpeg?auto=compress&cs=tinysrgb&w=400',
    author: 'Dr. Fatou Sarr',
    date: '2024-03-10',
    category: 'Histoire',
    readTime: '12 min'
  },
  {
    id: '2',
    title: 'La Gastronomie Sénégalaise : Un Voyage Culinaire',
    excerpt: 'Explorez les saveurs authentiques du Sénégal, du thiéboudiène aux yassa.',
    content: 'Contenu sur la gastronomie...',
    image: 'https://images.pexels.com/photos/8030834/pexels-photo-8030834.jpeg?auto=compress&cs=tinysrgb&w=400',
    author: 'Chef Moussa Ba',
    date: '2024-03-08',
    category: 'Culture',
    readTime: '8 min'
  },
  {
    id: '3',
    title: 'Architecture Coloniale de Saint-Louis',
    excerpt: 'Explorez l\'héritage architectural de Saint-Louis, ancienne capitale de l\'AOF.',
    content: 'Contenu complet sur l\'architecture...',
    image: 'https://images.pexels.com/photos/8030834/pexels-photo-8030834.jpeg?auto=compress&cs=tinysrgb&w=400',
    author: 'Marie Sané',
    date: '2024-03-05',
    category: 'Patrimoine',
    readTime: '10 min'
  },
  {
    id: '4',
    title: 'Les Griots : Gardiens de la Mémoire',
    excerpt: 'Découvrez le rôle essentiel des griots dans la préservation de l\'histoire orale.',
    content: 'Contenu sur les griots...',
    image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400',
    author: 'Ousmane Ba',
    date: '2024-02-28',
    category: 'Traditions',
    readTime: '15 min'
  },
  {
    id: '5',
    title: 'Artisanat Sénégalais : Entre Tradition et Modernité',
    excerpt: 'L\'évolution de l\'artisanat sénégalais et son importance dans l\'économie locale.',
    content: 'Contenu sur l\'artisanat...',
    image: 'https://images.pexels.com/photos/8964864/pexels-photo-8964864.jpeg?auto=compress&cs=tinysrgb&w=400',
    author: 'Khady Fall',
    date: '2024-02-20',
    category: 'Art',
    readTime: '12 min'
  },
  {
    id: '6',
    title: 'Les Royaumes du Sénégal Précolonial',
    excerpt: 'Plongez dans l\'histoire des grands royaumes qui ont façonné le Sénégal.',
    content: 'Contenu sur les royaumes...',
    image: 'https://images.pexels.com/photos/8552976/pexels-photo-8552976.jpeg?auto=compress&cs=tinysrgb&w=400',
    author: 'Dr. Amadou Cissé',
    date: '2024-02-15',
    category: 'Histoire',
    readTime: '18 min'
  }
];

// Mock data pour les lieux
export const mockPlaces = [
  {
    id: '1',
    name: 'Restaurant Le Ngor',
    type: 'restaurant',
    rating: 4.6,
    address: 'N\'Gor, Dakar',
    coordinates: { lat: 14.7525, lng: -17.5163 },
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=400',
    description: 'Cuisine française avec vue sur l\'océan',
    phone: '+221 33 820 1234',
    hours: '12:00 - 23:00',
    price: '€€€'
  },
  {
    id: '2',
    name: 'Hôtel Terrou-Bi',
    type: 'hotel',
    rating: 4.8,
    address: 'Almadies, Dakar',
    coordinates: { lat: 14.7392, lng: -17.5069 },
    image: 'https://images.pexels.com/photos/271618/pexels-photo-271618.jpeg?auto=compress&cs=tinysrgb&w=400',
    description: 'Hôtel de luxe face à la mer',
    phone: '+221 33 820 5678',
    hours: '24/7',
    price: '€€€€'
  },
  {
    id: '3',
    name: 'Monument de la Renaissance',
    type: 'monument',
    rating: 4.3,
    address: 'Ouakam, Dakar',
    coordinates: { lat: 14.7158, lng: -17.4933 },
    image: 'https://images.pexels.com/photos/8552976/pexels-photo-8552976.jpeg?auto=compress&cs=tinysrgb&w=400',
    description: 'Monument emblématique de 49 mètres de hauteur',
    phone: '+221 33 820 9012',
    hours: '09:00 - 18:00',
    price: '€€'
  },
  {
    id: '4',
    name: 'Île de Gorée',
    type: 'monument',
    rating: 4.9,
    address: 'Île de Gorée',
    coordinates: { lat: 14.6681, lng: -17.4025 },
    image: 'https://images.pexels.com/photos/8828593/pexels-photo-8828593.jpeg?auto=compress&cs=tinysrgb&w=400',
    description: 'Site historique classé au patrimoine mondial',
    phone: '+221 33 820 3456',
    hours: '08:00 - 19:00',
    price: '€€'
  },
  {
    id: '5',
    name: 'Restaurant Le Lagon',
    type: 'restaurant',
    rating: 4.6,
    address: 'N\'Gor, Dakar',
    coordinates: { lat: 14.7525, lng: -17.5163 },
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=400',
    description: 'Cuisine française avec vue sur l\'océan',
    phone: '+221 33 820 7890',
    hours: '12:00 - 23:00',
    price: '€€€'
  },
  {
    id: '6',
    name: 'Hôtel des Almadies',
    type: 'hotel',
    rating: 4.4,
    address: 'Almadies, Dakar',
    coordinates: { lat: 14.7392, lng: -17.5069 },
    image: 'https://images.pexels.com/photos/271618/pexels-photo-271618.jpeg?auto=compress&cs=tinysrgb&w=400',
    description: 'Hôtel de luxe face à la mer',
    phone: '+221 33 820 1357',
    hours: '24/7',
    price: '€€€€'
  }
];

// Mock data pour les jumelages
export const mockMatches = [
  {
    id: '1',
    local: {
      name: 'Aïcha Diop',
      location: 'Dakar',
      avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150'
    },
    compatibility: 95,
    reason: 'Vous partagez les mêmes intérêts pour la culture et l\'histoire du Sénégal',
    commonInterests: ['Culture', 'Histoire', 'Gastronomie']
  }
];
